### ISSUE TITLE
TypeError: #<Object> is not a constructor

### ISSUE THREAD

**Issue by chackerian** [mdtanrikulu/use-metamask#26]
I'm getting this error the first time using this package. I'm using the ethers Web3Interface

```
TypeError: #<Object> is not a constructor
    at _construct (useMetamask.js:18:1)
    at _callee$ (useMetamask.js:137:1)
    at tryCatch (runtime.js:63:1)
    at Generator.invoke [as _invoke] (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at asyncGeneratorStep (useMetamask.js:32:1)
    at _next (useMetamask.js:34:1)
    at useMetamask.js:34:1
    at new Promise (<anonymous>)
    at useMetamask.js:34:1
```

How can I resolve this issue?

**Comment by hveveris** [comment]
@chackerian 
`await connect(ethers.providers.Web3Provider);`

**Comment by mdtanrikulu** [comment]
Seems like it resolved, I am closing this issue, please re-open if reply above didn't help.
